name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ['self-hosted', 'Linux', 'flavor-8-16']
    container: tarantool/doc-builder:slim-4.2
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      S3_ENDPOINT_URL: ${{secrets.S3_ENDPOINT_URL}}
      S3_UPLOAD_PATH: ${{secrets.S3_UPLOAD_PATH}}
      S3_BUCKET: ${{secrets.S3_BUCKET}}
      INTERNALS_UPDATE_URL: ${{secrets.INTERNALS_UPDATE_URL}}
      INTERNALS_UPDATE_KEY: ${{secrets.INTERNALS_UPDATE_KEY}}
      BRANCH_NAME: latest
    steps:
      - uses: actions/checkout@v2

      - run: make -f ci.mk json
      - run: bash upload_output.sh
