name: Deploy branch

on:
  pull_request:
jobs:
  deploy-branch:
    runs-on: ['self-hosted', 'Linux', 'flavor-8-16']
    container: tarantool/doc-builder:slim-4.2
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      S3_ENDPOINT_URL: ${{secrets.S3_ENDPOINT_URL}}
      S3_UPLOAD_PATH: ${{secrets.S3_UPLOAD_PATH}}
      S3_BUCKET: ${{secrets.S3_BUCKET}}
      INTERNALS_UPDATE_URL: ${{secrets.INTERNALS_DEVELOP_UPDATE_URL}}
      INTERNALS_UPDATE_KEY: ${{secrets.INTERNALS_UPDATE_KEY}}
      BRANCH_NAME: test
    steps:
      - uses: actions/checkout@v2

      - name: Start dev server deployment
        uses: bobheadxi/deployments@v0.5.2
        id: deployment
        with:
          step: start
          token: ${{secrets.GITHUB_TOKEN}}
          env: ${{env.BRANCH_NAME}}
          ref: ${{github.head_ref}}

      - run: sphinx-build -b json source -d build/.doctrees build/json
      - run: bash upload_output.sh

      - name: update deployment status
        uses: bobheadxi/deployments@v0.5.2
        with:
          step: finish
          token: ${{secrets.GITHUB_TOKEN}}
          status: ${{job.status}}
          deployment_id: ${{steps.deployment.outputs.deployment_id}}
          env_url: https://docs.d.tarantool.io/en/dev/core/
