name: Deploy-branch

on:
  pull_request:
jobs:
  deploy-branch:
    runs-on: ['self-hosted', 'Linux', 'flavor-8-16']
    container: tarantool/doc-builder:slim-4.2
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
      ENDPOINT_URL: ${{secrets.ENDPOINT_URL}}
      S3_UPLOAD_PATH: ${{secrets.S3_UPLOAD_PATH}}
      S3_BUCKET: ${{secrets.S3_BUCKET}}
    steps:
      - uses: actions/checkout@v2

      - name: Set branch name from source branch
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV

      - run: sphinx-build -b json source -d build/.doctrees build/json
      - run: bash upload_output.sh
